"""empty message

Revision ID: 1c98d8195506
Revises: 
Create Date: 2024-12-01 08:52:30.648229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c98d8195506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=False),
    sa.Column('code_freezing_time', sa.DateTime(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_id'), 'evaluation', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userevaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('deployed_url', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userevaluation_id'), 'userevaluation', ['id'], unique=False)
    op.create_table('evaluationreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userevaluation_id', sa.Integer(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['userevaluation_id'], ['userevaluation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluationreport_id'), 'evaluationreport', ['id'], unique=False)
    op.create_table('evaluationstep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userevaluation_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_report', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['userevaluation_id'], ['userevaluation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userevaluation_id', 'step_name')
    )
    op.create_index(op.f('ix_evaluationstep_id'), 'evaluationstep', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluationstep_id'), table_name='evaluationstep')
    op.drop_table('evaluationstep')
    op.drop_index(op.f('ix_evaluationreport_id'), table_name='evaluationreport')
    op.drop_table('evaluationreport')
    op.drop_index(op.f('ix_userevaluation_id'), table_name='userevaluation')
    op.drop_table('userevaluation')
    op.drop_table('user')
    op.drop_index(op.f('ix_evaluation_id'), table_name='evaluation')
    op.drop_table('evaluation')
    # ### end Alembic commands ###
