"""empty message

Revision ID: 6655f5af0815
Revises: e3b4ce64f819
Create Date: 2024-12-04 07:22:22.633636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6655f5af0815'
down_revision: Union[str, None] = 'e3b4ce64f819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation', sa.Column('questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation', 'questions')
    # ### end Alembic commands ###
