"""empty message

Revision ID: 71c0f23a341c
Revises: 6655f5af0815
Create Date: 2024-12-09 08:24:17.457581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c0f23a341c'
down_revision: Union[str, None] = '6655f5af0815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation', sa.Column('project_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation', 'project_type')
    # ### end Alembic commands ###
