"""empty message

Revision ID: e3b4ce64f819
Revises: 786c91c348e7
Create Date: 2024-12-01 19:32:47.748519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3b4ce64f819'
down_revision: Union[str, None] = '786c91c348e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userevaluation_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userevaluation_id'], ['userevaluation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chathistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chatsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chathistory')
    op.drop_table('chatsession')
    # ### end Alembic commands ###
